name: Release

on:
    push:
        tags:
            - v*

jobs:
    release:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]

        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2 # Install pnpm using packageManager key in package.json

            - name: Use Node.js 18
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build
              run: pnpm build

            - name: Run Electron Builder
              run: |
                  case "${{ matrix.os }}" in
                      macos-latest) platform=mac ;;
                      ubuntu-latest) platform=linux ;;
                      windows-latest) platform=windows ;;
                  esac

                  pnpm electron-builder --$platform --publish always
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
