name: Release

on:
    push:
        tags:
            - v*

jobs:
    release:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Run Electron Builder
              run: |
                  case "${{ matrix.os }}" in
                      macos-latest) platform=mac ;;
                      ubuntu-latest) platform=linux ;;
                      windows-latest) platform=windows ;;
                  esac

                  pnpm install
                  pnpm build
                  pnpm electron-builder --$platform --publish always
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
